FROM ubuntu:17.04

MAINTAINER Theodore Kisner <tskisner@lbl.gov>

# Use bash

SHELL ["/bin/bash", "-c"]

# Install system dependencies.

RUN apt-get update \
    && apt-get install -y curl procps build-essential gfortran git subversion \
    autoconf automake libtool m4 cmake locales libgl1-mesa-glx xvfb \
    && rm -fr /var/lib/apt/lists/*

# Set up locales, to workaround a pip bug

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8 
ENV LANGUAGE en_US:en 
ENV LC_ALL en_US.UTF-8

# Install conda root environment

ENV PYTHONPATH ""
ENV PYTHONSTARTUP ""
ENV PYTHONNOUSERSITE "1"
ENV PYTHONUSERBASE "/tmp"

@conda_root3@

ENV ACCEPT_INTEL_PYTHON_EULA yes

ENV PATH="/conda/bin:${PATH}"

# Install conda packages.

@conda_pkgs@

# Copy MKL headers into conda root

@mkl_headers@

# Create working directory for builds

RUN mkdir -p /usr/src/work
WORKDIR /usr/src/work

# Copy the entry point and setup scripts

COPY dockerdata/entrypoint.sh /
COPY dockerdata/setup.sh /

# Set the entrypoint and default command

ENTRYPOINT ["/entrypoint.sh"]
CMD ["--help"]
